Amend deploy-flux.sh
hmcts/aks-sds-deploy pull request #119
Opened 2022-01-21 13:24 UTC by zc-hmcts

- add toffee to workaround

2022-01-21 13:28 UTC, timja commented on bootstrap/deploy-flux.sh
> +    kubectl apply -f https://raw.githubusercontent.com/hmcts/sds-flux-config/master/apps/toffee/identity/toffee-azure-identity.yaml
why?

2022-01-21 13:36 UTC, zc-hmcts commented on bootstrap/deploy-flux.sh
> +    kubectl apply -f https://raw.githubusercontent.com/hmcts/sds-flux-config/master/apps/toffee/identity/toffee-azure-identity.yaml
unable to recognize "STDIN": no matches for kind "AzureIdentity" in version "aadpodidentity.k8s.io/v1"

2022-01-21 14:05 UTC, timja commented on bootstrap/deploy-flux.sh
> +    kubectl apply -f https://raw.githubusercontent.com/hmcts/sds-flux-config/master/apps/toffee/identity/toffee-azure-identity.yaml
try restart the pod, or check the CRDs are ready

2022-01-21 15:03 UTC, zc-hmcts commented on bootstrap/deploy-flux.sh
> +    kubectl apply -f https://raw.githubusercontent.com/hmcts/sds-flux-config/master/apps/toffee/identity/toffee-azure-identity.yaml
it's from the build logs, building from scratch

2022-01-24 11:55 UTC, timja requested changes
we can't do this

2022-01-24 11:56 UTC, closed without merging