added new env folders & moved code from prior env folders
hmcts/aks-sds-deploy pull request #232
Opened 2022-09-08 14:55 UTC by narinder17

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-9696

### Change description ###
added new env folders & moved code from prior env folders
created new parameters

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

2022-09-12 14:03 UTC, hmcts-platform-operations commented
## Plan Result (sbox-00-genesis)




<pre><code>Plan: 7 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * module.genesis.azurerm_key_vault.key_vault
  * module.genesis.azurerm_key_vault_access_policy.developers_group_access_policy
  * module.genesis.azurerm_key_vault_access_policy.key_vault_access_policy
  * module.genesis.azurerm_key_vault_access_policy.ops_group_access_policy
  * module.genesis.azurerm_key_vault_access_policy.platform_operations
  * module.genesis.azurerm_resource_group.genesis_resource_group
  * module.genesis.random_id.random_id




<details><summary>Change Result (Click me)</summary>

```hcl

  # module.genesis.data.null_data_source.key_vault_outputs will be read during apply
  # (config refers to values not yet known)
 <= data "null_data_source" "key_vault_outputs" {
      + has_computed_default = (known after apply)
      + id                   = (known after apply)
      + inputs               = {
          + "azurerm_key_vault_id" = (known after apply)
        }
      + outputs              = (known after apply)
      + random               = (known after apply)
    }

  # module.genesis.azurerm_key_vault.key_vault will be created
  + resource "azurerm_key_vault" "key_vault" {
      + access_policy                   = (known after apply)
      + enabled_for_deployment          = true
      + enabled_for_disk_encryption     = true
      + enabled_for_template_deployment = true
      + id                              = (known after apply)
      + location                        = "uksouth"
      + name                            = "dtssharedservicessboxkv"
      + resource_group_name             = "genesis-rg"
      + sku_name                        = "standard"
      + soft_delete_retention_days      = 30
      + tags                            = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + tenant_id                       = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
      + vault_uri                       = (known after apply)

      + network_acls {
          + bypass                     = (known after apply)
          + default_action             = (known after apply)
          + ip_rules                   = (known after apply)
          + virtual_network_subnet_ids = (known after apply)
        }
    }

  # module.genesis.azurerm_key_vault_access_policy.developers_group_access_policy will be created
  + resource "azurerm_key_vault_access_policy" "developers_group_access_policy" {
      + id                 = (known after apply)
      + key_permissions    = [
          + "Encrypt",
        ]
      + key_vault_id       = (known after apply)
      + object_id          = "7bde62e7-b39f-487c-95c9-b4c794fdbb96"
      + secret_permissions = [
          + "List",
          + "Set",
        ]
      + tenant_id          = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
    }

  # module.genesis.azurerm_key_vault_access_policy.key_vault_access_policy will be created
  + resource "azurerm_key_vault_access_policy" "key_vault_access_policy" {
      + id                 = (known after apply)
      + key_permissions    = [
          + "Create",
          + "Decrypt",
          + "Delete",
          + "Encrypt",
          + "Get",
          + "Import",
          + "List",
          + "Purge",
          + "Recover",
          + "Restore",
          + "Sign",
          + "UnwrapKey",
          + "Update",
          + "Verify",
          + "WrapKey",
        ]
      + key_vault_id       = (known after apply)
      + object_id          = "18100ccb-fb74-4790-b836-4454445b56cb"
      + secret_permissions = [
          + "Backup",
          + "Delete",
          + "Get",
          + "List",
          + "Purge",
          + "Recover",
          + "Restore",
          + "Set",
        ]
      + tenant_id          = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
    }

  # module.genesis.azurerm_key_vault_access_policy.ops_group_access_policy will be created
  + resource "azurerm_key_vault_access_policy" "ops_group_access_policy" {
      + id                 = (known after apply)
      + key_permissions    = [
          + "Decrypt",
          + "Delete",
          + "Encrypt",
          + "Get",
          + "Import",
        ]
      + key_vault_id       = (known after apply)
      + object_id          = "af66f4e5-bd36-4ad9-a265-d9e7c947cbab"
      + secret_permissions = [
          + "Backup",
          + "Delete",
          + "Get",
          + "List",
          + "Purge",
          + "Recover",
          + "Restore",
          + "Set",
        ]
      + tenant_id          = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
    }

  # module.genesis.azurerm_key_vault_access_policy.platform_operations will be created
  + resource "azurerm_key_vault_access_policy" "platform_operations" {
      + certificate_permissions = [
          + "Backup",
          + "Create",
          + "Delete",
          + "DeleteIssuers",
          + "Get",
          + "GetIssuers",
          + "Import",
          + "List",
          + "ListIssuers",
          + "ManageContacts",
          + "ManageIssuers",
          + "Recover",
          + "Restore",
          + "SetIssuers",
          + "Update",
        ]
      + id                      = (known after apply)
      + key_permissions         = [
          + "Create",
          + "Delete",
          + "Encrypt",
          + "Decrypt",
          + "Get",
          + "Import",
          + "List",
          + "Recover",
          + "Restore",
          + "Update",
          + "Backup",
        ]
      + key_vault_id            = (known after apply)
      + object_id               = "e7ea2042-4ced-45dd-8ae3-e051c6551789"
      + secret_permissions      = [
          + "Backup",
          + "Delete",
          + "Get",
          + "List",
          + "Recover",
          + "Restore",
          + "Set",
        ]
      + tenant_id               = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
    }

  # module.genesis.azurerm_resource_group.genesis_resource_group will be created
  + resource "azurerm_resource_group" "genesis_resource_group" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "genesis-rg"
      + tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
    }

  # module.genesis.random_id.random_id will be created
  + resource "random_id" "random_id" {
      + b64_std     = (known after apply)
      + b64_url     = (known after apply)
      + byte_length = 6
      + dec         = (known after apply)
      + hex         = (known after apply)
      + id          = (known after apply)
      + keepers     = {
          + "subscription_id" = "subscriptions"
        }
    }

Plan: 7 to add, 0 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":232,"Program":"tfcmt","SHA1":"","Target":"sbox-00-genesis","Vars":{}} -->

2022-09-12 14:50 UTC, hmcts-platform-operations commented
## Plan Result (sbox-07-network-rg)




<pre><code>Plan: 1 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * azurerm_resource_group.network_resource_group




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_resource_group.network_resource_group will be created
  + resource "azurerm_resource_group" "network_resource_group" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "ss-sbox-network-rg"
      + tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":232,"Program":"tfcmt","SHA1":"","Target":"sbox-07-network-rg","Vars":{}} -->

2022-09-12 15:32 UTC, hmcts-platform-operations commented
## Plan Result (sbox-01-network)




<pre><code>Plan: 38 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * azurerm_private_dns_zone_virtual_network_link.link[&#34;sandbox.platform.hmcts.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.link[&#34;sbox.platform.hmcts.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;private.postgres.database.azure.com&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.blob.core.windows.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.database.windows.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.datafactory.azure.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.dev.azuresynapse.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.postgres.database.azure.com&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.redis.cache.windows.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.service.signalr.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.servicebus.windows.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.sql.azuresynapse.net&#34;]
  * azurerm_private_dns_zone_virtual_network_link.private_endpoint[&#34;privatelink.vaultcore.azure.net&#34;]
  * module.network.azurerm_route.additional_route[&#34;10_0_0_0&#34;]
  * module.network.azurerm_route.additional_route[&#34;172_16_0_0&#34;]
  * module.network.azurerm_route.additional_route[&#34;192_168_0_0&#34;]
  * module.network.azurerm_route.default_route
  * module.network.azurerm_route_table.route_table
  * module.network.azurerm_subnet.additional_subnets[&#34;api-management&#34;]
  * module.network.azurerm_subnet.additional_subnets[&#34;private-endpoints&#34;]
  * module.network.azurerm_subnet.additional_subnets[&#34;redis&#34;]
  * module.network.azurerm_subnet.additional_subnets[&#34;vh_private_endpoints&#34;]
  * module.network.azurerm_subnet.aks_00_subnet
  * module.network.azurerm_subnet.aks_01_subnet
  * module.network.azurerm_subnet.application_gateway_subnet
  * module.network.azurerm_subnet.iaas_subnet
  * module.network.azurerm_subnet.postgresql_subnet
  * module.network.azurerm_subnet_route_table_association.aks_00
  * module.network.azurerm_subnet_route_table_association.aks_01
  * module.network.azurerm_subnet_route_table_association.iaas
  * module.network.azurerm_subnet_route_table_association.postgresql
  * module.network.azurerm_virtual_network.virtual_network
  * module.vnet_peer_hub_sbox[&#34;ukSouth&#34;].azurerm_virtual_network_peering.initiator-To-target
  * module.vnet_peer_hub_sbox[&#34;ukSouth&#34;].azurerm_virtual_network_peering.target-To-initiator
  * module.vnet_peer_hub_sbox[&#34;ukWest&#34;].azurerm_virtual_network_peering.initiator-To-target
  * module.vnet_peer_hub_sbox[&#34;ukWest&#34;].azurerm_virtual_network_peering.target-To-initiator
  * module.vnet_peer_vpn.azurerm_virtual_network_peering.initiator-To-target
  * module.vnet_peer_vpn.azurerm_virtual_network_peering.target-To-initiator




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_private_dns_zone_virtual_network_link.link["sandbox.platform.hmcts.net"] will be created
  + resource "azurerm_private_dns_zone_virtual_network_link" "link" {
      + id                    = (known after apply)
      + name                  = "sssbox"
      + private_dns_zone_name = "sandbox.platform.hmcts.net"
      + registration_enabled  = false
      + resource_group_name   = "core-infra-intsvc-rg"
      + tags                  = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + virtual_network_id    = (known after apply)
    }

  # azurerm_private_dns_zone_virtual_network_link.link["sbox.platform.hmcts.net"] will be created
  + resource "azurerm_private_dns_zone_virtual_network_link" "link" {
      + id                    = (known after apply)
      + name                  = "sssbox"
      + private_dns_zone_name = "sbox.platform.hmcts.net"
      + registration_enabled  = false
      + resource_group_name   = "core-infra-intsvc-rg"
      + tags                  = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + virtual_network_id    = (known after apply)
    }

  # azurerm_private_dns_zone_virtual_network_link.private_endpoint["private.postgres.database.azure.com"] will be created
  + resource "azurerm_private_dns_zone_virtual_network_link" "private_endpoint" {
      + id                    = (known after apply)
      + name                  = "sssbox"
      + private_dns_zone_name = "private.postgres.database.azure.com"
      + registration_enabled  = false
      + resource_group_name   = "core-infra-intsvc-rg"
      + tags                  = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + virtual_network_id    = (known after apply)
    }

  # azurerm_private_dns_zone_virtual_network_link.private_endpoint["privatelink.blob.core.windows.net"] will be created
  + resource "azurerm_private_dns_zone_virtual_network_link" "private_endpoint" {
      + id                    = (known after apply)
      + name                  = "sssbox"
      + private_dns_zone_name = "privatelink.blob.core.windows.net"
      + registration_enabled  = false
      + resource_group_name   = "core-infra-intsvc-rg"
      + tags                  = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + virtual_network_id    = (known after apply)
    }

  # azurerm_private_dns_zone_virtual_network_link.private_endpoint["privatelink.database.windows.net"] will be created
  + resource "azurerm_private_dns_zone_virtual_network_link" "private_endpoint" {
      + id                    = (known after apply)
      + name                  = "sssbox"
      + private_dns_zone_name = "privatelink.database.windows.net"
      + registration_enabled  = false
      + resource_group_name   = "core-infra-intsvc-rg"
      + tags                  = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + virtual_network_id    = (known after apply)
    }

  # azurerm_private_dns_zone_virtual_network_link.private_endpoint["privatelink.datafactory.azure.net"] will be created
  + resource "azurerm_private_dns_zone_virtual_network_link" "private_endpoint" {
      + id                    = (known after apply)
      + name                  = "sssbox"
      + private_dns_zone_name = "privatelink.datafactory.azure.net"
      + registration_enabled  = false
      + resource_group_name   = "core-infra-intsvc-rg"
      + tags                  = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
      + virtual_network_id    = (known after apply)
    }

  # azurerm_private_dns_zone_virtual_network_link.private_endpoint["privatelink.dev.azuresynapse.net"] will be created
  +  [...]

2022-09-12 15:33 UTC, hmcts-platform-operations commented
## Plan Result (sbox-05-mis)




<pre><code>Plan: 16 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * azurerm_key_vault_access_policy.sops-policy
  * azurerm_key_vault_key.sops-key
  * azurerm_resource_group.application-mi
  * azurerm_role_assignment.Reader
  * azurerm_role_assignment.acme-vault-access
  * azurerm_role_assignment.genesis_managed_identity_operator
  * azurerm_role_assignment.global_registry_acrpull
  * azurerm_role_assignment.kubelet_uami_genesis
  * azurerm_role_assignment.log_analytics_role_MI
  * azurerm_role_assignment.log_analytics_role_aks_sp
  * azurerm_role_assignment.network_access
  * azurerm_role_assignment.project_registry_acrpull
  * azurerm_role_assignment.sbox_registry_acrpull[&#34;sbox&#34;]
  * azurerm_role_assignment.uami_rg_identity_operator
  * azurerm_user_assigned_identity.kubelet_uami
  * azurerm_user_assigned_identity.sops-mi




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_key_vault_access_policy.sops-policy will be created
  + resource "azurerm_key_vault_access_policy" "sops-policy" {
      + id                 = (known after apply)
      + key_permissions    = [
          + "Get",
          + "Encrypt",
          + "Decrypt",
          + "List",
        ]
      + key_vault_id       = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/genesis-rg/providers/Microsoft.KeyVault/vaults/dtssharedservicessboxkv"
      + object_id          = (known after apply)
      + secret_permissions = [
          + "Get",
          + "List",
        ]
      + tenant_id          = "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
    }

  # azurerm_key_vault_key.sops-key will be created
  + resource "azurerm_key_vault_key" "sops-key" {
      + curve              = (known after apply)
      + e                  = (known after apply)
      + id                 = (known after apply)
      + key_opts           = [
          + "decrypt",
          + "encrypt",
        ]
      + key_size           = 2048
      + key_type           = "RSA"
      + key_vault_id       = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/genesis-rg/providers/Microsoft.KeyVault/vaults/dtssharedservicessboxkv"
      + n                  = (known after apply)
      + name               = "sops-key"
      + public_key_openssh = (known after apply)
      + public_key_pem     = (known after apply)
      + version            = (known after apply)
      + versionless_id     = (known after apply)
      + x                  = (known after apply)
      + y                  = (known after apply)
    }

  # azurerm_resource_group.application-mi will be created
  + resource "azurerm_resource_group" "application-mi" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "managed-identities-sbox-rg"
      + tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
    }

  # azurerm_role_assignment.Reader will be created
  + resource "azurerm_role_assignment" "Reader" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (known after apply)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Reader"
      + scope                            = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/genesis-rg/providers/Microsoft.KeyVault/vaults/dtssharedservicessboxkv"
      + skip_service_principal_aad_check = (known after apply)
    }

  # azurerm_role_assignment.acme-vault-access will be created
  + resource "azurerm_role_assignment" "acme-vault-access" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (known after apply)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Key Vault Secrets User"
      + scope                            = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/sds-platform-sbox-rg/providers/Microsoft.KeyVault/vaults/acmedtssdssbox"
      + skip_service_principal_aad_check = (known after apply)
    }

  # azurerm_role_assignment.genesis_managed_identity_operator will be created
  + resource "azurerm_role_assignment" "genesis_managed_identity_operator" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (known after apply)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Managed Identity Operator"
      + scope                            = (known after apply)
      + skip_service_principal_aad_check = (known after apply)
    }

  # azurerm_role_assignment.global_registry_acrpull will be created
  + resource "azurerm_role_assignment" "global_registry_acrpull" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (known after apply)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "AcrPull"
      + scope                            = "/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/resourceGroups/rpe-acr-prod-rg"
      + skip_service_principal_aad_check = (known after apply)
    }

  # azurerm_role_assignment.kubelet_uami_genesis will be created
  + resource "azurerm_role_assignment" "kubelet_uami_genesis" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (known after apply)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Managed Identity Operator"
      + scope                            = (known after apply)
      + skip_service_principal_aad_check = (known after apply)
    }

  # azurerm_role_assignment.log_analytics_role_MI will be created
  + resource "azurerm_role_assignment" "log_analytics_role_MI" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (known after apply)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Log Analytics Contributor"
      + scope                            = "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/oms-automation/providers/Microsoft.OperationalInsights/workspaces/hmcts-sandbox"
      + skip_service_principal_aad_check = (known after apply)
    }

  # azurerm_role_assignment.log_analytics_role_aks_sp will be created
  + resource "azurerm_role_assignment" "log_analytics_role_aks_sp" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = (sensitive)
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Log Analytics Contributor"
      + scope                            = "/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/resourceGroups/oms-automation/pro [...]

2022-09-12 15:35 UTC, hmcts-platform-operations commented
## Plan Result (sbox-aks)




<pre><code>Plan: 13 to add, 0 to change, 0 to destroy.</code></pre>

* Create
  * azurerm_resource_group.disks_resource_group
  * azurerm_resource_group.kubernetes_resource_group[&#34;00&#34;]
  * azurerm_resource_group.kubernetes_resource_group[&#34;01&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster.kubernetes_cluster
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;linux&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;msnode&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting[0]
  * module.kubernetes[&#34;00&#34;].azurerm_role_assignment.node_infrastructure_update_scale_set
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster.kubernetes_cluster
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;linux&#34;]
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;msnode&#34;]
  * module.kubernetes[&#34;01&#34;].azurerm_monitor_diagnostic_setting.kubernetes_cluster_diagnostic_setting[0]
  * module.kubernetes[&#34;01&#34;].azurerm_role_assignment.node_infrastructure_update_scale_set




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_resource_group.disks_resource_group will be created
  + resource "azurerm_resource_group" "disks_resource_group" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "disks-sbox-rg"
      + tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
    }

  # azurerm_resource_group.kubernetes_resource_group["00"] will be created
  + resource "azurerm_resource_group" "kubernetes_resource_group" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "ss-sbox-00-rg"
      + tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
    }

  # azurerm_resource_group.kubernetes_resource_group["01"] will be created
  + resource "azurerm_resource_group" "kubernetes_resource_group" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "ss-sbox-01-rg"
      + tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
        }
    }

  # module.kubernetes["00"].data.azurerm_client_config.current will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_client_config" "current" {
      + client_id       = (known after apply)
      + id              = (known after apply)
      + object_id       = (known after apply)
      + subscription_id = (known after apply)
      + tenant_id       = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_key_vault.hmcts_access_vault will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_key_vault" "hmcts_access_vault" {
      + access_policy                   = (known after apply)
      + enable_rbac_authorization       = (known after apply)
      + enabled_for_deployment          = (known after apply)
      + enabled_for_disk_encryption     = (known after apply)
      + enabled_for_template_deployment = (known after apply)
      + id                              = (known after apply)
      + location                        = (known after apply)
      + name                            = "ca8140a9e09e2ee23f7abkv"
      + network_acls                    = (known after apply)
      + purge_protection_enabled        = (known after apply)
      + resource_group_name             = "azure-control-sbox-rg"
      + sku_name                        = (known after apply)
      + tags                            = (known after apply)
      + tenant_id                       = (known after apply)
      + vault_uri                       = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_key_vault_secret.aks_admin_group_id will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_key_vault_secret" "aks_admin_group_id" {
      + content_type   = (known after apply)
      + id             = (known after apply)
      + key_vault_id   = (known after apply)
      + name           = "aks-admin-rbac-group-id"
      + tags           = (known after apply)
      + value          = (sensitive value)
      + version        = (known after apply)
      + versionless_id = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_key_vault_secret.kubernetes_cluster_client_secret will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_key_vault_secret" "kubernetes_cluster_client_secret" {
      + content_type   = (known after apply)
      + id             = (known after apply)
      + key_vault_id   = (known after apply)
      + name           = "sp-token"
      + tags           = (known after apply)
      + value          = (sensitive value)
      + version        = (known after apply)
      + versionless_id = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_resource_group.disks_resource_group will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_resource_group" "disks_resource_group" {
      + id       = (known after apply)
      + location = (known after apply)
      + name     = "disks-sbox-rg"
      + tags     = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_resource_group.genesis_rg will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_resource_group" "genesis_rg" {
      + id       = (known after apply)
      + location = (known after apply)
      + name     = "genesis-rg"
      + tags     = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_resource_group.managed-identity-operator will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_resource_group" "managed-identity-operator" {
      + id       = (known after apply)
      + location = (known after apply)
      + name     = "managed-identities-sbox-rg"
      + tags     = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_resource_group.node_resource_group will be read during apply
  # (depends on a resource or a module with changes pending)
 <= data "azurerm_resource_group" "node_resource_group" {
      + id       = (known after apply)
      + location = (known after apply)
      + name     = "ss-sbox-00-aks-node-rg"
      + tags     = (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }

  # module.kubernetes["00"].data.azurerm_role_definition.builtin_role_definition will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_role_definition" "builtin_role_definition" {
      + assignable_scopes  = (known after apply)
      + description        = (known after apply)
  [...]

2022-09-23 09:52 UTC, timja commented on azure-pipelines.yml
> -                targetCommand: '-target azurerm_resource_group.kubernetes_resource_group["\"${{parameters.cluster}}\""] -target module.kubernetes["\"${{parameters.cluster}}\""] -target azurerm_role_a
this doesn't seem to have been ported across that I can see.

@msl8r is this still eneded?

2022-09-23 09:56 UTC, timja requested changes
Most of the plans look wrong. Please get this down to a zero diff on terraform.

The only one that is okay-ish is the postgres one but that could be fixed by running the master branch against sbox

2023-05-15 09:21 UTC, narinder17 commented
no longer required

2023-05-15 09:21 UTC, closed without merging