DTSPO-14865-replace-kured
hmcts/aks-sds-deploy pull request #562
Opened 2024-03-01 16:20 UTC by JoshuaGlassKainos

### Jira link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPO-14865

### Change description ###
added node_os_channel_upgrade, may need to update module not too sure.

### Checklist

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2024-03-01 16:23 UTC, hmcts-platform-operations commented
## Plan Result (Genesis)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":562,"Program":"tfcmt","SHA1":"","Target":"Genesis","Vars":{}} -->

2024-03-01 16:24 UTC, hmcts-platform-operations commented
## Plan Result (Network)




<pre><code>No changes. Your infrastructure matches the configuration.</code></pre>









<!-- github-comment: {"Command":"plan","PRNumber":562,"Program":"tfcmt","SHA1":"","Target":"Network","Vars":{}} -->

2024-03-01 16:27 UTC, hmcts-platform-operations commented
## Plan Result (Managed_Identity)




<pre><code>Plan: 0 to add, 1 to change, 0 to destroy.</code></pre>

* Update
  * azurerm_resource_group.application-mi




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_resource_group.application-mi will be updated in-place
  ~ resource "azurerm_resource_group" "application-mi" {
        id       = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/managed-identities-sbox-rg"
        name     = "managed-identities-sbox-rg"
      ~ tags     = {
          + "application"  = "core"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
          + "expiresAfter" = "3000-01-01"
          + "startupMode"  = "always"
        }
        # (1 unchanged attribute hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

</details>





<!-- github-comment: {"Command":"plan","PRNumber":562,"Program":"tfcmt","SHA1":"","Target":"Managed_Identity","Vars":{}} -->

2024-03-04 18:27 UTC, hmcts-platform-operations commented
## Plan Result (Aks)




<pre><code>Plan: 2 to add, 10 to change, 0 to destroy.</code></pre>

* Create
  * azurerm_resource_group.disks_resource_group
  * azurerm_role_assignment.disk
* Update
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster.kubernetes_cluster
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;arm&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;cronjob&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;linux&#34;]
  * module.kubernetes[&#34;00&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;msnode&#34;]
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster.kubernetes_cluster
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;arm&#34;]
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;cronjob&#34;]
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;linux&#34;]
  * module.kubernetes[&#34;01&#34;].azurerm_kubernetes_cluster_node_pool.additional_node_pools[&#34;msnode&#34;]




<details><summary>Change Result (Click me)</summary>

```hcl

  # azurerm_resource_group.disks_resource_group will be created
  + resource "azurerm_resource_group" "disks_resource_group" {
      + id       = (known after apply)
      + location = "uksouth"
      + name     = "disks-sbox-rg"
      + tags     = {
          + "application"  = "core"
          + "autoShutdown" = "true"
          + "builtFrom"    = "hmcts/aks-sds-deploy"
          + "businessArea" = "Cross-Cutting"
          + "criticality"  = "Low"
          + "environment"  = "sandbox"
          + "expiresAfter" = "3000-01-01"
        }
    }

  # azurerm_role_assignment.disk will be created
  + resource "azurerm_role_assignment" "disk" {
      + id                               = (known after apply)
      + name                             = (known after apply)
      + principal_id                     = "ba206872-8722-4375-bf4d-a28c39dff414"
      + principal_type                   = (known after apply)
      + role_definition_id               = (known after apply)
      + role_definition_name             = "Virtual Machine Contributor"
      + scope                            = (known after apply)
      + skip_service_principal_aad_check = (known after apply)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster.kubernetes_cluster will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
        id                                  = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/ss-sbox-00-rg/providers/Microsoft.ContainerService/managedClusters/ss-sbox-00-aks"
      ~ kubernetes_version                  = "1.28.5" -> "1.28"
        name                                = "ss-sbox-00-aks"
      + node_os_channel_upgrade             = "NodeImage"
        tags                                = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-sds-deploy"
            "businessArea" = "Cross-Cutting"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
        }
        # (30 unchanged attributes hidden)

      ~ default_node_pool {
            name                         = "system"
          ~ orchestrator_version         = "1.28.5" -> "1.28"
            tags                         = {
                "application"  = "core"
                "autoShutdown" = "true"
                "builtFrom"    = "hmcts/aks-sds-deploy"
                "businessArea" = "Cross-Cutting"
                "criticality"  = "Low"
                "environment"  = "sandbox"
                "expiresAfter" = "3000-01-01"
            }
            # (22 unchanged attributes hidden)
        }

        # (8 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["arm"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                      = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/ss-sbox-00-rg/providers/Microsoft.ContainerService/managedClusters/ss-sbox-00-aks/agentPools/arm"
        name                    = "arm"
      ~ orchestrator_version    = "1.28.5" -> "1.28"
        tags                    = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-sds-deploy"
            "businessArea" = "Cross-Cutting"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
        }
        # (25 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["cronjob"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                      = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/ss-sbox-00-rg/providers/Microsoft.ContainerService/managedClusters/ss-sbox-00-aks/agentPools/cronjob"
        name                    = "cronjob"
      ~ orchestrator_version    = "1.28.5" -> "1.28"
        tags                    = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-sds-deploy"
            "businessArea" = "Cross-Cutting"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
        }
        # (25 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["linux"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                      = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/ss-sbox-00-rg/providers/Microsoft.ContainerService/managedClusters/ss-sbox-00-aks/agentPools/linux"
        name                    = "linux"
      ~ orchestrator_version    = "1.28.5" -> "1.28"
        tags                    = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-sds-deploy"
            "businessArea" = "Cross-Cutting"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
        }
        # (25 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.kubernetes["00"].azurerm_kubernetes_cluster_node_pool.additional_node_pools["msnode"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pools" {
        id                      = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resourceGroups/ss-sbox-00-rg/providers/Microsoft.ContainerService/managedClusters/ss-sbox-00-aks/agentPools/msnode"
        name                    = "msnode"
      ~ orchestrator_version    = "1.28.5" -> "1.28"
        tags                    = {
            "application"  = "core"
            "autoShutdown" = "true"
            "builtFrom"    = "hmcts/aks-sds-deploy"
            "businessArea" = "Cross-Cutting"
            "criticality"  = "Low"
            "environment"  = "sandbox"
            "expiresAfter" = "3000-01-01"
        }
        # (25 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

  # module.kubernetes["01"].azurerm_kubernetes_cluster.kubernetes_cluster will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "kubernetes_cluster" {
        id                                  = "/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/resource [...]

2024-03-05 14:02 UTC, JoshuaGlassKainos commented
https://github.com/hmcts/aks-sds-deploy/blob/eb15d31d007eb03f283f8b2963f33f4c9ea1054b/components/aks/aks.tf#L141
`enable_node_os_channel_upgrade_nodeimage = var.enable_node_os_channel_upgrade_nodeimage`

this flag is permanently on if env is sandbox, it can be abstracted further by replacing it with a tfvars like the following `enable_node_os_channel_upgrade_nodeimage = true` in tfvars

2024-03-06 11:33 UTC, reespozzi requested changes

2024-03-06 11:33 UTC, reespozzi commented on components/aks/aks.tf
> +  # optional flag, if env is sbox then set flag to true
Would remove this comment, pretty clear in the code I think

2024-03-06 11:41 UTC, thomast1906 commented on components/aks/aks.tf
> +  # optional flag, if env is sbox then set flag to true
+1 most terraform should be made readable without the need for comments

2024-03-06 13:40 UTC, reespozzi commented
Does the feature need adding to sbox aks before merging this or?

2024-03-06 16:03 UTC, JoshuaGlassKainos commented
> Does the feature need adding to sbox aks before merging this or?

Will need to look into this further, but I think `Microsoft.ContainerService/NodeOsUpgradeChannelPreview` will need to enabled on sbox cluster for the `node_os_channel_upgrade` to take effect

2024-03-06 16:10 UTC, JoshuaGlassKainos commented
Sbox will need the following commands to be ran to ensure the preview feature `Microsoft.ContainerService/NodeOsUpgradeChannelPreview` is active on that cluster.
[link to ref](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-os-image#register-nodeosupgradechannelpreview)

Enable preview feature on the cluster with the following 
`az feature register --namespace "Microsoft.ContainerService" --name "NodeOsUpgradeChannelPreview"`

Register preview feature with the following
`az provider register --namespace Microsoft.ContainerService`

2024-03-07 13:31 UTC, JoshuaGlassKainos reviewed
comments removed and fat file

2024-03-07 14:58 UTC, reespozzi approved these changes

2024-03-07 14:58 UTC, reespozzi commented
Could you FMT again please? Not sure it's been run

2024-03-07 15:14 UTC, merged